language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
matrix:
    include:
        - python: "3.7"
          dist: xenial
          sudo: true
install:
    - pip3 install -r requirements.txt
script:
    - python -c "import onioff;"